### ISSUE TITLE
problem:No module named 'lr_utils'

### ISSUE THREAD

**Issue by saitobay** [XingxingHuang/deeplearning.ai#1]
In NeuralNetwork&DeepLearning___Week2(Logistic+Regression+with+a+Neural+Network+mindset),
"from lr_utils import load_dataset“ failed,No module named 'lr_utils' .
Anyone help me out? Many Thanks.

**Comment by Peison** [comment]
i met the same problem today,had you fixed it ?

**Comment by cjcandctr** [comment]
You may find the answer from the course forum "https://www.coursera.org/learn/neural-networks-deep-learning/discussions/weeks/2/threads/qJ9EBIZDEeeNeRJP10SOQA".  Also downloading this repository and run locally, I suppose we won't meet this issue again.

**Comment by XingxingHuang** [comment]
File has been added,  thank you for add the issue. (Sorry I did not notice you have add issues in here.)

**Comment by ravin018** [comment]
hey guys, where can i get the files added for this issue ? seems like the code is now deleted ?

**Comment by ghost** [comment]
@ravin018 file of lr_utils.py
https://github.com/Shyarnis1/coursera-deep-learning/blob/master/Neural%20Networks%20and%20Deep%20Learning/Logistic%20Regression%20as%20a%20Neural%20Network/lr_utils.py

**Comment by webdesigns** [comment]
I need lr_utils.py. Can anyone help plz.

**Comment by SaiSaradindTadimalla** [comment]
Hey I have - No module named 'lr_utils' issue.....a little help please
