### ISSUE TITLE
How to download All resourse from Coursera Notebook server?

### ISSUE THREAD

**Issue by cjcandctr** [XingxingHuang/deeplearning.ai#2]
Huangxingxing您好，
我试着在Coursera Notebook server上浏览整个目录结构，能够看到整个课程的资源。 但是只能选中，删除，没有下载链接。 请问您是如何都下载下来的呢？ 
多谢～

**Comment by XingxingHuang** [comment]
@cjcandctr 你好，我是每个文件单独下来的。方法是进入notebook页面之后点击File>Open。随后你就可以看到每个文件了，单选每个文件就可以看到Download选项然后下载。
