### ISSUE TITLE
关于作业答案

### ISSUE THREAD

**Issue by Peison** [XingxingHuang/deeplearning.ai#3]
你好，看到你Readme上写着已经把答案删除，为什么我下载的文件中还包含着答案，请问怎么才能下到没有答案的版本

**Comment by cjcandctr** [comment]
仔细看下   其实不包含答案原文件也在里面的...

**Comment by XingxingHuang** [comment]
答案应该都删除了，如果你发现哪里包含答案请指出。 @Peison 。  @cjcandctr 谢谢你的帮忙
