### ISSUE TITLE
Momentum

### ISSUE THREAD

**Issue by king33yoyo** [XingxingHuang/deeplearning.ai#5]
![image](https://user-images.githubusercontent.com/18387267/30797830-f5f14eb2-a209-11e7-9692-c2fea3c2d5d1.png)

As the above formula show, vdw[ l ] is just correlation with vdw[ l ] and dW, but I think vdw should be a correlation with vdw[ l-1 ]. Am I wrong?

**Comment by XingxingHuang** [comment]
I think you are right, the left side of the equation should be (L + 1). Could you point out where these equations are from. I will correct them in the text. @king33yoyo

**Comment by king33yoyo** [comment]
The equations in Optimization+methods.ipynb. But I think again, the equations are just for convenience to code. Maybe they are not wrong.

**Comment by XingxingHuang** [comment]
Perfect. I will close the issue. Let me know if you have more questions.
