### ISSUE TITLE
little mistake in "deeplearning.ai/1_Neural Networks and Deep Learning/week2/Python Basics with Numpy/Python+Basics+With+Numpy+v3.ipynb"

### ISSUE THREAD

**Issue by kite8** [XingxingHuang/deeplearning.ai#6]
Thanks "up-zhu"~~~

I found the Sigmoid.png couldn't display.
I found the code is  

> <img src="images/Sigmoid.png" style="width:500px;height:228px;"

I think it should be

><img src="Sigmoid.png" style="width:500px;height:228px;"

or move the pitcure to the images folder.

**Comment by XingxingHuang** [comment]
Thank you very much. You suggestions are quite valuable. Fixed already. Let me know if you have any questions.
