### ISSUE TITLE
第一课第三周编程作业报错

### ISSUE THREAD

**Issue by seed-fe** [XingxingHuang/deeplearning.ai#9]
您好，开始做第一课第三周的作业时遇到一个问题：
运行
# Visualize the data:
plt.scatter(X[0, :], X[1, :], c=Y, s=40, cmap=plt.cm.Spectral);
这一部分代码会报一长串错误，最后的是
ValueError: c of shape (1, 400) not acceptable as a color sequence for x with size 400, y with size 400
然后也画不出花的形状，请问这个问题是什么情况，该如何解决啊？感激~

**Comment by XingxingHuang** [comment]
请查看邮件。可以到这个github下载更完整的notebook。
 https://github.com/shahariarrabby/deeplearning.ai

**Comment by seed-fe** [comment]
感谢回复，c=Y改成c=Y.reshape(400,)解决了
